source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "0.10.1"
gem "jekyll-remote-theme"
gem "jekyll-seo-tag"

# Windows / JRuby support
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "wdm", "~> 0.1", platforms: [:mingw, :mswin, :x64_mingw]
